"""Default configuration for llm-council.

The defaults assume the user has native CLI access to Claude Code, Codex, and
Gemini CLI. OpenRouter and local providers are available only when explicitly
selected by mode or participant name.
"""

DEFAULT_CONFIG: dict = {
    "version": 1,
    "transcripts_dir": ".llm-council/runs",
    "defaults": {
        "mode": "quick",
        "read_only": True,
        "synthesize": False,
        "origin_policy": "any",
        "max_concurrency": 4,
        "transparent": False,
        "max_deliberation_rounds": 2,
    },
    "participants": {
        "claude": {
            "type": "cli",
            "family": "claude",
            "origin": "US / Anthropic",
            "command": "claude",
            "args": [
                "-p",
                "--permission-mode",
                "plan",
                "--tools",
                "Read,Grep,Glob,LS",
                "--no-session-persistence",
            ],
            "model": None,
            "timeout": 240,
            "max_prompt_chars": 120_000,
            "read_only": True,
            "stdin_prompt": True,
            "env_passthrough": ["ANTHROPIC_API_KEY"],
        },
        "codex": {
            "type": "cli",
            "family": "codex",
            "origin": "US / OpenAI",
            "command": "codex",
            "args": [
                "exec",
                "--sandbox",
                "read-only",
                "--ask-for-approval",
                "never",
                "--ephemeral",
                "--cd",
                "{cwd}",
                "-",
            ],
            "model": None,
            "timeout": 240,
            "read_only": True,
            "stdin_prompt": True,
            "env_passthrough": ["OPENAI_API_KEY"],
        },
        "gemini": {
            "type": "cli",
            "family": "gemini",
            "origin": "US / Google",
            "command": "gemini",
            "args": [
                "--approval-mode",
                "plan",
            ],
            "model": None,
            "timeout": 240,
            "read_only": True,
            "stdin_prompt": True,
            "env_passthrough": ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
        },
        "deepseek_v4_pro": {
            "type": "openrouter",
            "family": "deepseek",
            "origin": "China / DeepSeek",
            "model": "deepseek/deepseek-v4-pro",
            "input_per_million": 0.435,
            "output_per_million": 0.87,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "deepseek_v4_flash": {
            "type": "openrouter",
            "family": "deepseek",
            "origin": "China / DeepSeek",
            "model": "deepseek/deepseek-v4-flash",
            "input_per_million": 0.14,
            "output_per_million": 0.28,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "qwen_coder_plus": {
            "type": "openrouter",
            "family": "qwen",
            "origin": "China / Alibaba Qwen",
            "model": "qwen/qwen3-coder-plus",
            "input_per_million": 0.65,
            "output_per_million": 3.25,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "qwen_coder_flash": {
            "type": "openrouter",
            "family": "qwen",
            "origin": "China / Alibaba Qwen",
            "model": "qwen/qwen3-coder-flash",
            "input_per_million": 0.195,
            "output_per_million": 0.975,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "qwen_coder_free": {
            "type": "openrouter",
            "family": "qwen",
            "origin": "China / Alibaba Qwen",
            "model": "qwen/qwen3-coder:free",
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
            "deprecated": "Account-dependent free route; use qwen_coder_flash for reliable cheap defaults.",
        },
        "glm_5_1": {
            "type": "openrouter",
            "family": "glm",
            "origin": "China / Z.ai",
            "model": "z-ai/glm-5.1",
            "input_per_million": 1.05,
            "output_per_million": 3.50,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "glm_4_7_flash": {
            "type": "openrouter",
            "family": "glm",
            "origin": "China / Z.ai",
            "model": "z-ai/glm-4.7-flash",
            "input_per_million": 0.06,
            "output_per_million": 0.40,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "kimi_k2_6": {
            "type": "openrouter",
            "family": "kimi",
            "origin": "China / Moonshot AI",
            "model": "moonshotai/kimi-k2.6",
            "input_per_million": 0.7448,
            "output_per_million": 4.655,
            "api_key_env": "OPENROUTER_API_KEY",
            "timeout": 180,
            "read_only": True,
        },
        "local_qwen_coder": {
            "type": "ollama",
            "family": "qwen",
            "origin": "China / Alibaba Qwen",
            "model": "qwen3-coder-next:q4_K_M",
            "base_url": "http://localhost:11434",
            "timeout": 180,
            "read_only": True,
        },
    },
    "modes": {
        "quick": {
            "strategy": "other_cli_peers",
            "description": "Ask the other two native CLIs from the current CLI.",
        },
        "plan": {
            "strategy": "other_cli_peers",
            "add": ["deepseek_v4_pro"],
            "description": "Premium local CLI peers plus DeepSeek for independent planning.",
        },
        "review": {
            "strategy": "other_cli_peers",
            "add": ["qwen_coder_plus"],
            "description": "CLI peers plus Qwen coding model.",
        },
        "review-cheap": {
            "participants": [
                "deepseek_v4_flash",
                "qwen_coder_flash",
                "glm_4_7_flash",
            ],
            "description": "Cheap hosted breadth reviewers.",
        },
        "diverse": {
            "strategy": "other_cli_peers",
            "add": ["deepseek_v4_pro", "glm_5_1", "kimi_k2_6"],
            "description": "Cross-lab planning diversity.",
        },
        "private-local": {
            "participants": ["local_qwen_coder"],
            "description": "Local-only private pass. Requires the model/runtime to exist.",
        },
        "us-only": {
            "strategy": "other_cli_peers",
            "origin_policy": "us",
            "description": "Use only US-origin native CLI participants.",
        },
        "deliberate": {
            "strategy": "other_cli_peers",
            "add": ["deepseek_v4_pro"],
            "deliberate": True,
            "description": "Expensive opt-in second round when first-round responses disagree.",
        },
    },
}
