"""OKF blast-radius context enrichment (opt-in).

When a council run includes a git diff and `okf_context` is enabled, the
orchestrator derives the symbols touched by the diff, looks up their one-hop
caller/callee neighborhood in an OKF knowledge bundle (generated by the
external `okf-rs` binary), and renders a compact signatures+locators excerpt
that `context.build_prompt` appends after the Git Diff section.

Invariants (see CLAUDE.md):
- Opt-in and default OFF everywhere; when disabled the prompt is byte-identical.
- Fail-soft: every OKF problem (missing binary, generation failure/timeout,
  no bundle, no matched concepts, no prompt headroom) degrades to "run
  proceeds exactly as today plus a diagnostic status dict".
- Never writes into the operator's project: ephemeral bundles go to a
  tempdir via `okf-rs generate <root> -o <tmpdir> --no-cache` (the
  `--no-cache` flag is load-bearing — without it okf-rs drops
  `.okf-cache.json` in the project root) and are removed in a `finally`.
- Ephemeral-first: the feature only runs when a diff exists, which means the
  working tree differs from HEAD for exactly the files under review — so a
  committed bundle is used only as a fallback (marked stale when its
  `source_revision` is not HEAD).

The machine interface is concept-file frontmatter (`resource:
path#Lstart-Lend` plus `relationships.calls/called_by` target ids) — the
okf-rs query subcommands have no JSON output mode.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from llm_council.blocking import check_cancelled, run_process

DEFAULT_OKF_BINARY = "okf-rs"
DEFAULT_OKF_GENERATE_TIMEOUT_SECONDS = 20.0
# Bound generator lifetime even when config requests an excessive timeout.
# Async callers run preparation in a cancellable worker; synchronous callers
# retain the same ceiling.
OKF_GENERATE_TIMEOUT_CEILING_SECONDS = 120.0
DEFAULT_OKF_MAX_EXCERPT_CHARS = 12_000
# Below this much prompt headroom the excerpt cannot say anything useful;
# skip with status `excerpt_over_budget` rather than emit a fragment.
OKF_EXCERPT_FLOOR_CHARS = 500
# Safety caps for the bundle walk (a generated bundle for a large monorepo
# can hold tens of thousands of concept files).
MAX_CONCEPT_FILES_SCANNED = 5_000
MAX_BUNDLE_ENTRIES_SCANNED = 20_000
MAX_FRONTMATTER_BYTES = 16_384
MAX_GENERATE_CAPTURE_BYTES = 8_192
# Only fine-grained concepts participate in range matching. Module/package
# concepts span whole files and would match every diff in the file,
# drowning the excerpt in noise.
_MATCHABLE_ID_PREFIXES = ("functions/", "classes/")

OKF_SECTION_HEADER = "## OKF Blast Radius (call-graph context)"

_RESOURCE_RE = re.compile(r"^(?P<path>.+?)#L(?P<start>\d+)-L(?P<end>\d+)$")
_HUNK_RE = re.compile(r"^@@ -\d+(?:,\d+)? \+(?P<start>\d+)(?:,(?P<count>\d+))? @@")
# Sentinel range for deleted files: callers of a deleted symbol are the
# highest-value blast radius, so the whole old file is considered touched.
_DELETED_FILE_RANGE = (1, 10**9)


@dataclass(frozen=True)
class OkfSettings:
    """Resolved feature settings for one run."""

    enabled: bool
    binary: str = DEFAULT_OKF_BINARY
    generate_timeout_seconds: float = DEFAULT_OKF_GENERATE_TIMEOUT_SECONDS
    max_excerpt_chars: int = DEFAULT_OKF_MAX_EXCERPT_CHARS


@dataclass
class Concept:
    """One concept file's machine-relevant fields."""

    concept_id: str
    path: str
    start: int
    end: int
    signature: str | None = None
    calls: list[str] = field(default_factory=list)
    called_by: list[str] = field(default_factory=list)


def resolve_okf_settings(
    config: dict[str, Any], mode: str, override: bool | None
) -> OkfSettings:
    """Resolve the feature toggle with None-aware precedence.

    `override` (CLI flag / MCP argument) > `modes.<mode>.okf_context` >
    `defaults.okf_context` > OFF. Not an `or` chain: an explicit `false`
    at a higher-priority layer must override a `true` below it (same
    contract as `independent_review`).
    """

    defaults = config.get("defaults", {}) or {}
    if override is not None:
        enabled = bool(override)
    else:
        mode_value = (config.get("modes", {}) or {}).get(mode, {}).get("okf_context")
        if mode_value is not None:
            enabled = bool(mode_value)
        else:
            enabled = bool(defaults.get("okf_context"))
    return OkfSettings(
        enabled=enabled,
        binary=str(defaults.get("okf_binary") or DEFAULT_OKF_BINARY),
        generate_timeout_seconds=min(
            float(
                defaults.get("okf_generate_timeout_seconds")
                or DEFAULT_OKF_GENERATE_TIMEOUT_SECONDS
            ),
            OKF_GENERATE_TIMEOUT_CEILING_SECONDS,
        ),
        max_excerpt_chars=int(
            defaults.get("okf_max_excerpt_chars") or DEFAULT_OKF_MAX_EXCERPT_CHARS
        ),
    )


def touched_ranges_from_diff(raw_diff: str) -> dict[str, list[tuple[int, int]]]:
    """Map a unified diff to {repo-relative path: [(start, end), ...]}.

    Ranges are on the new side of the diff (matching an ephemeral bundle
    generated from the working tree). Deleted files map their OLD path to a
    whole-file sentinel range so callers of removed symbols still match.
    Binary files, pure renames, and mode-only changes contribute nothing.
    The parser keys only on `diff --git` / `---` / `+++` / `@@` prefixes;
    truncation notices and `\\ No newline` markers are ignored. The same
    path may appear in both the staged and unstaged halves of the raw text;
    range lists are merged per path.
    """

    touched: dict[str, list[tuple[int, int]]] = {}
    old_path: str | None = None
    new_path: str | None = None

    def _clean(token: str) -> str | None:
        token = token.strip()
        if token.startswith('"') and token.endswith('"') and len(token) >= 2:
            token = token[1:-1]
        if token == "/dev/null":
            return None
        for prefix in ("a/", "b/"):
            if token.startswith(prefix):
                return token[len(prefix):]
        return token

    for line in raw_diff.splitlines():
        if line.startswith("diff --git "):
            old_path = None
            new_path = None
            continue
        if line.startswith("--- "):
            old_path = _clean(line[4:])
            continue
        if line.startswith("+++ "):
            new_path = _clean(line[4:])
            if new_path is None and old_path is not None:
                # Deleted file: the whole old file counts as touched.
                touched.setdefault(old_path, []).append(_DELETED_FILE_RANGE)
            continue
        match = _HUNK_RE.match(line)
        if match and new_path is not None:
            start = int(match.group("start"))
            count_text = match.group("count")
            count = int(count_text) if count_text is not None else 1
            # A pure-deletion hunk (`+c,0`) still touches the enclosing
            # symbol; record a point range at the anchor line.
            start = max(start, 1)
            end = start + max(count, 1) - 1
            touched.setdefault(new_path, []).append((start, end))
    return touched


def _parse_frontmatter(text: str) -> dict[str, Any] | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    try:
        loaded = yaml.safe_load(text[3:end])
    except yaml.YAMLError:
        return None
    return loaded if isinstance(loaded, dict) else None


# Signatures come from repo content and land unfenced in the prompt;
# single-line by construction, but cap length so a pathological (or
# hostile) declaration cannot dominate the excerpt.
_MAX_SIGNATURE_CHARS = 300


def _extract_signature(body: str) -> str | None:
    """Pull the backticked signature line under the `# Signature` heading."""

    anchor = body.find("# Signature")
    if anchor < 0:
        return None
    for line in body[anchor:].splitlines()[1:]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            return None
        return stripped.strip("`")[:_MAX_SIGNATURE_CHARS] or None
    return None


def _relationship_targets(entries: Any) -> list[str]:
    targets: list[str] = []
    if not isinstance(entries, list):
        return targets
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        target = entry.get("target")
        if not isinstance(target, str) or not target:
            continue
        # Future-proofing: okf-rs 0.7.0 uses string confidence
        # ("exact"/"semantic"); drop only if a numeric confidence below
        # 0.5 ever appears.
        confidence = entry.get("confidence")
        if isinstance(confidence, (int, float)) and not isinstance(confidence, bool):
            if confidence < 0.5:
                continue
        targets.append(target)
    return targets


def _read_bundle_text(path: Path, boundary: Path) -> str:
    """Read a bounded prefix of a regular file within the bundle boundary."""
    check_cancelled()
    resolved = path.resolve(strict=True)
    if not resolved.is_relative_to(boundary.resolve()) or not resolved.is_file():
        raise ValueError(f"Bundle file is outside its boundary or not regular: {path}")
    with resolved.open("rb") as handle:
        return handle.read(MAX_FRONTMATTER_BYTES).decode("utf-8", errors="replace")


def _concept_paths(bundle_dir: Path) -> list[Path]:
    """Bound enumeration before sorting; never follow directory/file symlinks."""
    paths: list[Path] = []
    pending = [bundle_dir / kind for kind in ("functions", "classes")]
    scanned = 0
    while pending:
        check_cancelled()
        directory = pending.pop()
        if directory.is_symlink() or not directory.is_dir():
            continue
        with os.scandir(directory) as entries:
            for entry in entries:
                check_cancelled()
                scanned += 1
                if scanned > MAX_BUNDLE_ENTRIES_SCANNED:
                    raise ValueError("OKF bundle exceeds directory-entry scan limit")
                if entry.is_dir(follow_symlinks=False):
                    pending.append(Path(entry.path))
                elif (
                    entry.is_file(follow_symlinks=False)
                    and entry.name.endswith(".md") and entry.name != "index.md"
                ):
                    paths.append(Path(entry.path))
                    if len(paths) > MAX_CONCEPT_FILES_SCANNED:
                        raise ValueError("OKF bundle exceeds concept-file scan limit")
    return sorted(paths)


def load_concepts(bundle_dir: Path) -> dict[str, Concept]:
    """Index a bundle's function/class concept files by concept id.

    Concept ids mirror the relationship `target` format: the file path
    relative to the bundle root, without the `.md` suffix. Files with
    missing or malformed frontmatter, or without a parseable
    `resource: path#Lstart-Lend`, are skipped.
    """

    concepts: dict[str, Concept] = {}
    for md_path in _concept_paths(bundle_dir):
        try:
            text = _read_bundle_text(md_path, bundle_dir)
        except (OSError, ValueError):
            continue
        frontmatter = _parse_frontmatter(text)
        if frontmatter is None:
            continue
        resource = frontmatter.get("resource")
        match = _RESOURCE_RE.match(resource) if isinstance(resource, str) else None
        if match is None:
            continue
        relationships = frontmatter.get("relationships") or {}
        if not isinstance(relationships, dict):
            relationships = {}
        concept_id = md_path.relative_to(bundle_dir).with_suffix("").as_posix()
        concepts[concept_id] = Concept(
            concept_id=concept_id,
            path=match.group("path").replace("\\", "/"),
            start=int(match.group("start")),
            end=int(match.group("end")),
            signature=_extract_signature(text),
            calls=_relationship_targets(relationships.get("calls")),
            called_by=_relationship_targets(relationships.get("called_by")),
        )
    return concepts


def match_concepts(
    concepts: dict[str, Concept],
    touched: dict[str, list[tuple[int, int]]],
) -> list[Concept]:
    """Concepts whose resource range intersects any touched range."""

    normalized = {path.replace("\\", "/"): ranges for path, ranges in touched.items()}
    matched: list[Concept] = []
    for concept in concepts.values():
        if not concept.concept_id.startswith(_MATCHABLE_ID_PREFIXES):
            continue
        ranges = normalized.get(concept.path)
        if not ranges:
            continue
        if any(start <= concept.end and concept.start <= end for start, end in ranges):
            matched.append(concept)
    matched.sort(key=lambda c: (c.path, c.start, c.concept_id))
    return matched


def _neighbor_line(neighbor_id: str, concepts: dict[str, Concept]) -> str:
    neighbor = concepts.get(neighbor_id)
    if neighbor is None:
        return f"  - {neighbor_id}"
    locator = f"{neighbor.path}#L{neighbor.start}-L{neighbor.end}"
    if neighbor.signature:
        return f"  - `{neighbor.signature}` — {locator}"
    return f"  - {neighbor_id} — {locator}"


def render_okf_section(
    matched: list[Concept],
    concepts: dict[str, Concept],
    *,
    budget: int,
    source_revision: str | None,
    source_kind: str,
    stale: bool,
) -> tuple[str | None, int]:
    """Render the excerpt; returns (text or None, concepts rendered).

    Deterministic: matched order is preserved (already sorted), neighbors
    are sorted by concept id, and truncation drops whole trailing concept
    blocks with a counted marker. The returned text never exceeds
    `budget`.
    """

    if not matched:
        return None, 0
    revision_label = source_revision or "unknown"
    stale_note = (
        " The bundle predates the current HEAD; treat line numbers as"
        " approximate."
        if stale
        else ""
    )
    header = (
        f"{OKF_SECTION_HEADER}\n\n"
        "One-hop call-graph neighborhood of the symbols touched by the "
        "diff, derived from an OKF knowledge bundle (revision "
        f"{revision_label}, {source_kind}). Line locators come from the "
        "bundle; verify against the working tree before citing them as "
        f"evidence.{stale_note}"
    )
    blocks: list[str] = []
    for concept in matched:
        lines = [f"### {concept.concept_id}"]
        if concept.signature:
            lines.append(f"- signature: `{concept.signature}`")
        lines.append(f"- resource: {concept.path}#L{concept.start}-L{concept.end}")
        if concept.called_by:
            lines.append("- called_by:")
            lines.extend(
                _neighbor_line(nid, concepts) for nid in sorted(concept.called_by)
            )
        if concept.calls:
            lines.append("- calls:")
            lines.extend(
                _neighbor_line(nid, concepts) for nid in sorted(concept.calls)
            )
        blocks.append("\n".join(lines))

    rendered = header
    included = 0
    total = len(blocks)
    for block in blocks:
        marker = (
            f"\n\n[okf excerpt truncated: showing {included + 1} of {total} "
            "touched concepts]"
        )
        candidate = rendered + "\n\n" + block
        # Reserve marker space unless this is the final block.
        reserve = 0 if included + 1 == total else len(marker)
        if len(candidate) + reserve > budget:
            break
        rendered = candidate
        included += 1
    if included == 0:
        return None, 0
    if included < total:
        rendered += (
            f"\n\n[okf excerpt truncated: showing {included} of {total} "
            "touched concepts]"
        )
    return rendered, included


def find_bundle(cwd: Path) -> tuple[Path, str | None] | None:
    """Locate a pre-existing bundle (fallback path only).

    Checks `okf.toml`'s `output` key at `cwd`, then `cwd/knowledge`. A
    directory counts as a bundle only when it holds an `index.md`. Returns
    (bundle_root, source_revision from the index frontmatter, or None).
    """

    candidates: list[Path] = []
    okf_toml = cwd / "okf.toml"
    if okf_toml.is_file():
        try:
            import tomllib

            output = tomllib.loads(_read_bundle_text(okf_toml, cwd)).get("output")
            if isinstance(output, str) and output:
                resolved = (cwd / output).resolve()
                # okf.toml lives in the reviewed repo and may be hostile: an
                # absolute or `../` output value must not aim the concept
                # walk outside cwd (the same boundary allow_outside_cwd
                # enforces for --context files).
                try:
                    inside = resolved.is_relative_to(cwd.resolve())
                except (OSError, ValueError):
                    inside = False
                if inside:
                    candidates.append(resolved)
        except (OSError, ValueError):
            pass
    candidates.append(cwd / "knowledge")
    for candidate in candidates:
        candidate = candidate.resolve()
        if not candidate.is_relative_to(cwd.resolve()):
            continue
        index = candidate / "index.md"
        if not index.is_file():
            continue
        revision: str | None = None
        try:
            frontmatter = _parse_frontmatter(_read_bundle_text(index, candidate))
        except (OSError, ValueError):
            continue
        if frontmatter is not None:
            raw_revision = frontmatter.get("source_revision")
            if isinstance(raw_revision, str) and raw_revision:
                revision = raw_revision
        return candidate, revision
    return None


def _head_revision(cwd: Path) -> str | None:
    # Reuse context's git plumbing (scrubbed env, timeout, repo pre-check).
    from llm_council.context import _git_output

    output = _git_output(cwd, ["rev-parse", "HEAD"])
    return output.strip() if output else None


def generate_ephemeral_bundle(
    cwd: Path, out_dir: Path, *, binary: str, timeout: float
) -> tuple[Path | None, str | None, str | None]:
    """Generate a working-tree bundle into `out_dir` (caller-owned).

    Returns (bundle_dir, failure_status, detail). The caller owns
    `out_dir`'s lifecycle — `build_okf_section` wraps it in a
    `tempfile.TemporaryDirectory` context manager so cleanup survives any
    exception, including BaseException (2026-08-31 council finding: an
    mkdtemp here with cleanup delegated across the return boundary leaked
    on Ctrl-C). `--no-cache` keeps `.okf-cache.json` out of the project
    root; `-o` keeps the bundle itself out.

    Output capture is disk-backed with a bounded decode, following
    `context._run_git`'s documented pattern: `capture_output=True` would
    buffer a malfunctioning generator's entire output in memory, and
    pipes held by surviving grandchildren could block past our own
    timeout — temp files have neither problem.
    """

    if shutil.which(binary) is None:
        return None, "binary_missing", f"{binary} not found on PATH"
    env = os.environ.copy()
    env["GIT_TERMINAL_PROMPT"] = "0"
    try:
        with (
            tempfile.TemporaryFile(mode="w+b") as stdout_file,
            tempfile.TemporaryFile(mode="w+b") as stderr_file,
        ):
            completed = run_process(
                [binary, "generate", str(cwd), "-o", str(out_dir), "--no-cache"],
                cwd=str(cwd),
                env=env,
                stdin=subprocess.DEVNULL,
                stdout=stdout_file,
                stderr=stderr_file,
                timeout=timeout,
            )
            # Decode only the stderr TAIL — vendor error lines sit at the
            # end of a failing run's output.
            stderr_file.seek(0, os.SEEK_END)
            stderr_size = stderr_file.tell()
            stderr_file.seek(max(0, stderr_size - MAX_GENERATE_CAPTURE_BYTES))
            stderr_tail = (
                stderr_file.read().decode("utf-8", errors="replace").strip()
            )
    except subprocess.TimeoutExpired:
        return None, "generate_timeout", f"exceeded {timeout}s"
    except OSError as exc:
        return None, "generate_failed", str(exc)
    if completed.returncode != 0:
        return None, "generate_failed", stderr_tail or f"exit {completed.returncode}"
    # okf-rs writes the bundle directly into -o; tolerate a nested
    # `knowledge/` layout in case a future version changes that.
    boundary = out_dir.resolve()
    for candidate in (out_dir, out_dir / "knowledge"):
        try:
            resolved = candidate.resolve(strict=True)
            if not resolved.is_relative_to(boundary):
                continue
            _read_bundle_text(resolved / "index.md", boundary)
        except (OSError, ValueError, RuntimeError):
            continue
        return resolved, None, None
    return None, "generate_failed", "no index.md in generated output"


def build_okf_section(
    cwd: Path,
    raw_diff: str,
    settings: OkfSettings,
    *,
    headroom: int,
) -> tuple[str | None, dict[str, Any]]:
    """Produce (section text or None, diagnostic status dict).

    The broad `except Exception` is deliberate and unique to this entry
    point: the fail-soft invariant requires that no OKF problem can ever
    fail the council run. Do not narrow it. (BaseException — e.g. a
    Ctrl-C — deliberately propagates; the TemporaryDirectory context
    manager still cleans up on that path.)
    """

    try:
        if not raw_diff.strip():
            return None, {"status": "no_diff"}
        budget = min(settings.max_excerpt_chars, headroom)
        if budget < OKF_EXCERPT_FLOOR_CHARS:
            return None, {"status": "excerpt_over_budget", "headroom": headroom}

        touched = touched_ranges_from_diff(raw_diff)
        if not touched:
            return None, {"status": "no_matched_concepts"}

        # Ephemeral-first: a diff means the working tree differs from HEAD
        # for exactly the files under review, so any committed bundle is
        # wrong about them. Fall back to it only when generation fails.
        with tempfile.TemporaryDirectory(prefix="llm-council-okf-") as tmp:
            bundle_dir, failure, detail = generate_ephemeral_bundle(
                cwd,
                Path(tmp),
                binary=settings.binary,
                timeout=settings.generate_timeout_seconds,
            )
            source_kind = "ephemeral working-tree generation"
            source_revision = _head_revision(cwd)
            stale = False
            status = "attached"
            if bundle_dir is None:
                fallback = find_bundle(cwd)
                if fallback is None:
                    return None, {
                        "status": failure or "generate_failed",
                        "detail": detail,
                    }
                bundle_dir, source_revision = fallback
                source_kind = "pre-existing bundle"
                # HEAD equality does not prove freshness for the dirty
                # source under review. Only this run's generation does.
                stale = True
                status = "stale_attached"

            concepts = load_concepts(bundle_dir)
            matched = match_concepts(concepts, touched)
            if not matched:
                return None, {"status": "no_matched_concepts"}
            text, rendered_count = render_okf_section(
                matched,
                concepts,
                budget=budget,
                source_revision=source_revision,
                source_kind=source_kind,
                stale=stale,
            )
            if text is None:
                return None, {"status": "excerpt_over_budget", "headroom": headroom}
            return text, {
                "status": status,
                "concepts": rendered_count,
                "matched": len(matched),
                "chars": len(text),
                "source_revision": source_revision,
                "source": (
                    "ephemeral" if source_kind.startswith("ephemeral") else "existing"
                ),
                "stale": stale,
            }
    except Exception as exc:  # noqa: BLE001 — fail-soft invariant, see docstring
        return None, {"status": "internal_error", "detail": repr(exc)}
